### ISSUE TITLE
api-version (2.1) cannot be greater than -language-version (1.9)

### ISSUE THREAD

**Issue by ByteByteBrew** [mcarleio/konvert#113]
Configure in example directory

```
tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions.jvmTarget = "21"
    kotlinOptions.javaParameters = true
    compilerOptions {
        apiVersion = org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_1
        languageVersion = KotlinVersion.KOTLIN_2_1
        jvmTarget = JvmTarget.JVM_21
        freeCompilerArgs.add("-Xuse-fir-lt=false")
    }
}
```

Incompatible versions

```
> Task :checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :kspKotlin FAILED
e: -api-version (2.1) cannot be greater than -language-version (1.9)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':kspKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 184ms
1 actionable task: 1 executed

```

**Comment by mcarleio** [comment]
The problem is your requirement `apiVersion = KotlinVersion.KOTLIN_2_1`.
If you comment this out, it should work as usual.

With this setting, every library you want to use must be build with Kotlin 2.1 as the target, which Konvert is currently not.

The reason for that is that there were issues/complexity with the migration to Kotlin 2.x and not all libraries and plugins supported the new language version.

But the goal and plan is to update Konvert to the newest Kotlin version as soon as possible.
