### ISSUE TITLE
Access Modifiers - extension functions

### ISSUE THREAD

**Issue by dawidbladek0831** [mcarleio/konvert#180]
Hi, i have a question regarding the visibility of generated methods.  

For example, given the following models:
```java
@KonvertTo(User::class)  
data class UserDto(  
  val id: Long,  
  val username: String,  
  val password: String
)
internal data class User(  
  val id: UserId,  
  val username: Username,  
  val password: Password
)
```

The declared converter generates the following extension function:
```java
@GeneratedKonverter(priority = 3_000)  
public fun UserDto.toUser(): User = User(  
  id = UserId(id),  
  username = Username(username),  
  password = Password(password)
)
```

However, this results in a compilation error:
```
'public' function exposes its 'internal' return type 'User'.
```
This happens because the `User` class is marked as `internal`.

Question, would it be possible to configure the visibility of the generated methods (for both `@KonvertFrom` and `@KonvertTo`)?

**Comment by mcarleio** [comment]
should work with version 4.3.1 :)
